<?php

/**
 * @file
 * Contains axl_page_json.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function axl_page_json_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the axl_page_json module.
    case 'help.page.axl_page_json':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Competency Check Module') . '</p>';
      return $output;

    default:
  }
}

